# Site settings
title: "Armada BJJ"
email: contact@armadabjj.com
description: >-
  Premier Brazilian Jiu-Jitsu academy offering world-class training
  in a welcoming, family-friendly environment.
baseurl: ""
url: "https://armadabjj.github.io"
github_username: armadabjj
instagram_username: armadabjj

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages compatibility
safe: true
incremental: false

# Language settings
languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localizations: ["javascript", "images", "css"]

# Collections
collections:
  instructors:
    output: true
    permalink: /:collection/:name/
  programs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "fr"
      type: "posts"
    values:
      layout: "post"
      lang: "fr"
  - scope:
      path: ""
      type: "instructors"
    values:
      layout: "instructor"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"

# Navigation
header_pages:
  - about.md
  - programs.md
  - instructors.md
  - schedule.md
  - pricing.md
  - blog.md
  - contact.md

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/